config/routes.rb
Rails.application.routes.draw do
  root to: 'users#welcome'
  resources :users do 
    get :confirm_email
  end
  resources :manufacturers
  resources :cards
  resources :occasions
  resources :aisles

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get 'logout', to: 'sessions#destroy'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/aisle.rb
class Aisle < ApplicationRecord
    has_many :cards 
    has_many :occasions, through: :cards
    has_many :manufacturers, through: :cards
    validates_presence_of :aisle_number
    validates_uniqueness_of :aisle_number, :message => "Already Entered"
    validates :aisle_number, numericality: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  $status = ()
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :occasion
    belongs_to :aisle
    belongs_to :manufacturer
    # validates_presence_of :sku
    validates_presence_of :occasion_id
    validates_presence_of :manufacturer_id
    validates_presence_of :aisle_id
    validates :in_stock, numericality: { only_integer: true }
    validates_presence_of :description
    validates :description, length: { maximum: 150 }
    has_one_attached :avatar
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
    has_many :cards 
    has_many :aisles, through: :cards
    validates_presence_of :name 
    validates_uniqueness_of :name, :message => "Already Listed"
end

app/models/occasion.rb
class Occasion < ApplicationRecord
    has_many :cards
    has_many :aisles, through: :cards 
    validates_presence_of :name_of
    validates_uniqueness_of :name_of

    scope :order_by, -> (attribute) {order(attribute)}
end

app/models/user.rb
class User < ApplicationRecord
    serialize :notes
    has_secure_password
    validates_presence_of :store_id, :message => "not entered"
    validates_presence_of :password, :message => "not entered"
    validates_presence_of :EmployeeInit, :message => "not entered"
    validates :notes, length: { maximum: 150 }

    private
end

app/controllers/aisles_controller.rb
class AislesController < ApplicationController
    before_action :set_aisle, only: [ :show, :edit, :destroy, :update ]

    def new 
        @aisle = Aisle.new
    end 

    def create 
        @aisle = Aisle.new(aisle_params) 
        if @aisle.save 
            redirect_to root_path, notice: "Aisle added"
        else 
            render :new 
        end
    end 

    def destroy 
    end 

    def show 
    end 

    def update
        if @aisle.update(aisle_params)
            redirect_to root_path, notice: "update recorded"
        else
            render :edit
        end
    end 

    private 

    def aisle_params 
        params.require(:aisle).permit(:aisle_number)
    end

    def set_aisle 
        @aisle = Aisle.find(params[:id])
    end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def update_notice
        $status << "#{@card.sku} updated"
    end 

    def require_login
        redirect_to root_path unless session.include? :user_id
    end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    before_action :set_card, only: [:show, :edit, :update, :destroy]
    after_action :update_notice, only: [:create, :update, :destroy ]
    def new 
        @card = Card.new
    end

    def create 
        @card = Card.new(card_params)
        if @card.save
            @sku = Faker::Barcode.ean_with_composite_symbology(13)
            @card.sku = @sku
            @card.save 
            redirect_to cards_path, notice: "Item #{@sku} Added"
        else
            render :new, notice: "Item not added. Try again"
        end 
    end 

    def edit 
    end 

    def update 
        if @card.update(card_params)
            redirect_to cards_path, notice: "Item #{@card.sku} Updated"
        else
            render :edit, notice: "record not updated"
        end
    end 

    def show 
    end 

    def destroy
        @card.destroy
        redirect_to root_path
    end 

    def index 
        @cards = Card.all
    end 

    private 
    def card_params
        params.require(:card).permit(:description, :in_stock, :aisle_id, :card, :occasion_id, :sku, :manufacturer_id, :avatar)
    end

    def set_card 
        @card = Card.find(params[:id])
    end 

    # def update_notice
    #     $status << "#{@card.sku} updated"
    # end 

end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
before_action :set_manufacturer, only: [ :show, :edit, :destroy, :update ]

    def new 
        @manufacturer = Manufacturer.new
    end  

    def create 
        @manufacturer = Manufacturer.new(manufacturer_params)
        if @manufacturer.save 
            redirect_to cards_path, notice: "Manufacturer Added" 
        else 
            render :new
        end
    end 

    def index 
        @manufacturer = Manufacturer.all
    end 

    def edit
    end 

    def destory 
        @manufacturer.destroy
    end 

    def show
    end 

    def update 
        if @manufacturer.update(manufacturer_params)
            redirect_to cards_path, notice: "Item #{@manufacturer.name} Updated"
        else
            render :edit, notice: "record not updated"
        end

    end 


    private 

    def manufacturer_params 
        params.require(:manufacturer).permit(:name)
    end 

    def set_manufacturer 
        @manufacturer = Manufacturer.find(params[:id])
    end


end

app/controllers/occasions_controller.rb
class OccasionsController < ApplicationController
    before_action :set_occasion, only: [ :show, :edit, :destroy, :update ]

    def index 
        @occasion = Occasion.all
    end 

    def new 
        @occasion = Occasion.new
    end 

    def create 
        @occasion = Occasion.new(occasion_params)
        if @occasion.save 
            redirect_to new_occasion_path, notice: "Occasion Added" 
        else 
            redirect_to new_occasion_path, notice: "Occasion Not Added"
        end
    end 

    def show 
    end 

    def edit 
    end 

    def update 
    end 

    def destroy
    end 

    private 

    def occasion_params 
        params.require(:occasion).permit(:name_of)
    end 
    
    # probably not needed...
    def occasion_name=(name)
        self.occasion = Occasion.find_or_create(:name => name)
        self.occasion << occasion 
    end 

    def set_occasion 
        @occasion = Occasion.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


    def new 
    end 

    def create
        @user = User.find_by_store_id(params[:store_id])
        if @user && @user.authenticate(params[:password])
            $status = ()
            session[:user_id] = @user.EmployeeInit
            UserMailer.aisle_inventory.deliver_now
            redirect_to cards_path, notice: "Welcome"
        else

          redirect_to login_path, notice: "Access Denied"
        end
    end

    def destroy
        session.destroy
        UserMailer.activity_report.deliver_now
        redirect_to root_path, notice: "Goodbye"
      end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def welcome 
         flash.notice = "Aisle Inventory - 2021  ©"
    end 

    def new 
        @user = User.new
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            UserMailer.aisle_inventory.deliver_now
            session[:user_id] = @user.EmployeeInit
            redirect_to cards_path, notice: "Welcome"
        else
            render :new, notice: "Access Denied"
        end
    end 

    private 

    def user_params 
        params.require(:user).permit(:password, :store_id, :notes, :EmployeeInit, :password_digest)
    end     
end

app/helpers/aisles_helper.rb
module AislesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/aisles/_errors.html.erb
<% if @aisle.errors.any? %>
<div id="error-messages">
    <ul>
    <% @aisle.errors.full_messages.each do |msg| %>
      <li><%= flash.notice = "#{msg}" %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  

app/views/aisles/new.html.erb
<% render 'errors' %>
<div class= "whiteboard">
<center><h2>update</h2></center>
    <center><%= form_with model: @aisle do |f| %>
    <p>Add Aisle<br></p>
    <small> only enter aisle number</small><br>
    <%= f.text_field :aisle_number%>
    <%= f.submit "Done"%>
 <%end%>
 </center>
</div>

app/views/cards/_error.html.erb
<% if @card.errors.any? %>
<div id="error_explanation">
    <ul>
    <% @card.errors.full_messages.each do |msg| %>
      <li><%= flash.notice = "#{msg}" %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

app/views/cards/index.html.erb
<div class= "whiteboard">
<center><h2>Card Index</h2></center>

</div>

app/views/cards/new.html.erb
<%=render  '/layouts/add_occasion' %>
<% render 'error' %>
   <div class= "details">
    <center><%= form_with model: @card do |f| %>
        <center>Select Occasion:</center><br>
        <%=f.collection_select(:occasion_id, Occasion.all, :id, :name_of) %><br>
        <br>
        Manufacturer:
        <%=f.collection_select(:manufacturer_id, Manufacturer.all, :id, :name, :include_blank => true) %><br>
        <br>
        <%= f.label :in_stock %>
        <%= f.text_field :in_stock %><br>
<br>
        <%= f.label :aisle_id%> Number
        <%=f.collection_select(:aisle_id, Aisle.all, :id, :aisle_number, :include_blank => true) %><br>

    <br>
        <%= f.label "Stock Image" %><br>
        <%= f.file_field :avatar %><br>
        <br>
        <%= f.label :"Description" %><br>
        <%=f.text_area :description, size: "25x9" %><br>
        <br>
        <%= f.submit "Add Product"%>
    <%end%></center>
    </div>

app/views/cards/show.html.erb
<%= render partial: '/layouts/profile', locals: {card: @card} %>

app/views/layouts/_add_card.html.erb
<%= f.fields_for :name_of do |t| %>
    <li>
    <%= t.label :"Occasion type" %>
    <%= t.text_field [:occasion][][:name_of] %>

    <%= t.label :"Occasion name" %>
    <%= t.text_field [:occasion][:name_of][] %>          
    </li>
  <% end %>

app/views/layouts/_add_cards.html.erb
<% render '/cards/error' %>
   <div class= "details">
    <center><%= form_with model: @card do |f| %>
        <center>Select Occasion:</center><br>
        <%=f.collection_select(:occasion_id, Occasion.order("name_of"), :id, :name_of) %><br>
        <br>
        Manufacturer:
        <%=f.collection_select(:manufacturer_id, Manufacturere.all, :id, :name, :include_blank => true) %><br>
        <br>
        <%= f.label :in_stock %>
        <%= f.text_field :in_stock %><br>
<br>
        <%= f.label :aisle_id%> Number
        <%=f.collection_select(:aisle_id, Aisle.all, :id, :aisle_number, :include_blank => true) %><br>

    <br>
        <%= f.label "Stock Image" %><br>
        <%= f.file_field :avatar %><br>
        <br>
        <%= f.label :"Description" %><br>
        <%=f.text_area :description, size: "25x9" %><br>
        <br>
        <%= f.submit "Add Product"%>
    <%end%></center>
    </div>

app/views/layouts/_profile.html.erb
<div class= "details">
<%= @card.description %><br>
Primary Occasion: <%= @card.occasion.name_of %><br>
Located in Aisle: <%= @card.aisle.aisle_number %><br>
Total in Stock: <%= @card.in_stock %> <br>
<br>
<br>
<div class="frame">
<% if @card.avatar.attached?%>
<image src="<%=(url_for(@card.avatar))%>"> 
<% end%>
<%= @card.updated_at %>
</div>
<br>
<%=link_to "Update inventory", root_path %> <br>
<%=link_to "Back", occasions_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%=stylesheet_link_tag 'application', media: 'all'%>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <div class='calculator'>
      <div class='display backlight'>
      <br>
      <center><% flash.each do |type, msg| %>
        <div class="error-messages">
          <%= msg %>
        </div>
      <% end %>
</center>  
       </div>
        <%= yield %>

        <section class="app">
    <aside class="sidebar">
         <header>
         <br>
      </header>
    <nav class="sidebar-nav">
 <br>
 <br>
 <br>
      <ul>
        <li>
          <a href="#"><i class="ion-bag"></i> <span></span></a>
          <ul class="nav-flyout">
            <li class="nav-add"><b><u>Adjustments</u></b>
            </li>
            <li>
              <%=link_to "By Occasion", occasions_path %>
            </li>
            <li>
              <%= link_to "By Manufacturer", manufacturers_path %>
            </li>
            <li>
            </li>
          </ul>
        </li>
        <li>
          <ul class="nav-flyout">
            <li>
          </ul>
        </li>
        <li class="nav-add"><b><u>Locator</u></b>
        </li>
        <li>
          <a href="#"><i class="ion-ios-medical-outline"></i> <span class="">By Ocassion</span></a>
        </li>
      <li>
      <a href="#"><i class="ion-ios-medical-outline"></i> <span class="">Accessories</span></a>
    </li>
    <li>
    <a href="#"><i class="ion-ios-medical-outline"></i> <span class="">By SKU</span></a>
  </li>

      </ul>
      <ul class="nav-flyout">
            <li>
          </ul>
        </li>
        <li class="nav-add"><b><u>Aisle Access</u></b>
        </li>
        <li>
          <small><%=link_to "Login", login_path %></small>
        </li>
        <li></li>
        <li class="nav-standout"><b><u>ADD</u></b>
        <li>
          <small><%=link_to "User", new_user_path%></small>
        </li>
        <li>
        <small><%=link_to "Manufacturer", new_manufacturer_path%></small>
      </li>
      <li>
      <small><%=link_to "Add Aisle", new_aisle_path%></small>
    </li>
    <li>
      <small><%=link_to "Occasion", new_occasion_path%></small>
    </li>
    <li>
    <small><%=link_to "Card SKU", new_card_path%></small>
  </li>
      <li></li>
        <li>
        <li class="nav-add"><b><u><%=link_to "Exit Aisle", logout_path %></u></b></li>
      <li>
      <a href="#"><i class="ion-ios-medical-outline"></i> <span class=""></span></a>
    </li>

      </ul>
    </nav>
  </aside>

        </section>
    </div>
  </body>
</html>

app/views/manufacturers/_errors.html.erb
<% if @manufacturer.errors.any? %>
<div id="error_explanation">
    <ul>
    <% @manufacturer.errors.full_messages.each do |msg| %>
      <li><%= flash.notice = "#{msg}" %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  

app/views/manufacturers/index.html.erb
<div class= "whiteboard">
<ul class= "occasion-list">
<center><% @manufacturer.each do |manufacturer| %>
    <ol><%= link_to "Remove #{manufacturer.name}", manufacturer_path(manufacturer),
    method: :delete,
    data: { confirm: "Permanently Delete #{manufacturer.name}?" } %></li><br>
    <li><%= link_to "Edit Title of  #{manufacturer.name}", edit_manufacturer_path(manufacturer) %></li>
    </ol> <br>
    <br>
    <%end%>
</ul>
<%= link_to "back", root_path %>
</center>
</div>

app/views/manufacturers/new.html.erb
<% render 'errors' %>
<div class= "whiteboard">
<center><h2>update</h2></center>
    <center><%= form_with model: @manufacturer do |f| %>
    <p><b>Enter Manufacture Name</b><br></p>
    <%= f.text_field :name%>
    <%= f.submit "Done"%>
 <%end%>
 </center>
</div>

app/views/occasions/_errors.html.erb
<% if @occasion.errors.any? %>
<div id="error_explanation">
    <ul>
    <% @occasion.errors.full_messages.each do |msg| %>
      <li><%= flash.notice = "#{msg}" %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

app/views/occasions/index.html.erb
<div class= "whiteboard">
<ul class= "occasion-list">
<center><% @occasion.each do |occasion| %>
    <ol><%= link_to "Remove #{occasion.name_of}", occasion_path(occasion),
    method: :delete,
    data: { confirm: "All SKUs will be orphaned" } %></li><br>
    <li><%= link_to "Relist #{occasion.name}", edit_occasion_path(occasion) %></li>
    </ol>
    <%end%>
</ul>
<%= link_to "back", root_path %>
</center>
</div>

app/views/occasions/new.html.erb
<% render 'errors' %>
<div class= "whiteboard">
<center><h2>Occasions</h2></center>
    <center><%= form_with model: @occasion do |f| %>
    <ol>
        <li><small>Check Spelling</small></li>
        <li><small>Start Name With Cap. Letters</small></li>
    </ol>
    <%= f.label :"Name Of Occasion" %>
    <%= f.text_field :name_of %><br>
    <%= f.submit "Add Occasion"%>
 <%end%>
 </center>
 <%= link_to "Current Listed Occasions", occasions_path %>

</div>

app/views/users/_errors.html.erb
  <% if @user.errors.any? %>
<div id="error_explanation">
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= flash.notice = "#{msg}" %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

app/views/users/new.html.erb
<% render '/users/errors' %>
<div class= "whiteboard">
<center><h2>Enter Store Code</h2></center>
    <center><%= form_with model: @user do |f| %>
    <p>Access Num -- StoreID -- EmployeeID<br></p>
    <%= f.password_field :access_id%>
    <%= f.text_field :store_id %>
    <%= f.text_field :EmployeeInit %>
    <%= f.submit "OK"%>
 <%end%>
 </center>
</div>

app/views/users/welcome.html.erb
<%= render '/layouts/open' %>